package pojo;
// Generated Mar 1, 2017 2:30:09 AM by Hibernate Tools 4.3.1



/**
 * Kontakt generated by hbm2java
 */
public class Kontakt  implements java.io.Serializable {


     private Integer id;
     private Korisnik korisnik;
     private String name;
     private String lastName;
     private String email;
     private String phoneNumber;

    public Kontakt() {
    }

    public Kontakt(Korisnik korisnik, String name, String lastName, String email, String phoneNumber) {
       this.korisnik = korisnik;
       this.name = name;
       this.lastName = lastName;
       this.email = email;
       this.phoneNumber = phoneNumber;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }




}


