package pojo;
// Generated Mar 1, 2017 2:30:09 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Korisnik generated by hbm2java
 */

public class Korisnik  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String email;
     private String phoneNumber;
     private Set kontakts = new HashSet(0);

    public Korisnik() {
    }

    public Korisnik(String username, String password, String email, String phoneNumber, Set kontakts) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.kontakts = kontakts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Set getKontakts() {
        return this.kontakts;
    }
    
    public void setKontakts(Set kontakts) {
        this.kontakts = kontakts;
    }




}


